# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
      - id: detect-private-key
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: name-tests-test
      - id: check-ast

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: []
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.982"
    hooks:
      - id: mypy
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
